### ISSUE TITLE
New standardization options in PubChem

### ISSUE THREAD

**Issue by schymane** [ZeroPM-H2020/pcapi#1] opened 2022-04-27 08:00 UTC
@RaoulWolf @sarahehaleZeroPM @hansarp now we can post issues here too, I'm cross-linking this to our issue here: 
https://github.com/RaoulWolf/pcapi/issues/1

**Comment by RaoulWolf** [comment] 2022-05-02 07:17
The functionality is now implemented as `post_to_standardize()` since pull request [08dc5a0](https://github.com/ZeroPM-H2020/pcapi/commit/08dc5a0e39f310a5e5101dd41f39a2c097a54e47)! 

Make sure to give it a go and see if it works as intended. The original JSON provided by the API was not nicely formatted, so a lot of subjective decision were made in the implementation of the function. 

Closing the issue now

**Closed as completed by RaoulWolf** 2022-05-02 07:17 UTC
